### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by BrendanBenshoof** [ipfs/python-ipfs-api#3]
I'm able to schedule time to work on this project now, and I have a goal list that is mostly accomplished by @amstocker. (context: https://github.com/BrendanBenshoof/ipfs_scratch/issues/1)

The big things that may be handled well, but I need to figure out and insure are:

- Error Handling (do we provide useful Exception (codes or types) both when requests fails and when ipfs returns an error? How does the generalized "command type" model interact with ipfs command specific

- Documentation? We essentially want to re-document every ipfs command with context on what is returned by our api. Inline pydoc doc-strings are a little harder because of the model @amstocker used (which I actually really like). I might just go ahead and add them to the "COMMANDS" section of client.py following the associated definition and in the worst case I'll have to compile a documentation page myself.

- Python 3 compatibility
    - Looks like there is a lot of work to do on this front. I am still getting a more solid understanding of what.

**Comment by amstocker** [comment]
Thanks for your help!  As it turns out I need to study for the math GRE in the next few weeks so I'll only have some short bursts of time to work on this going forward.

- Error-handling should be straight-forward.  It seems that most user errors are returned as json so we could check for a "Message" and "Code" field.  For example if you use cat on an invalid multihash it returns:

.. code-block

    {u'Message': u'invalid ipfs ref path', u'Code': 0}

**Comment by moreati** [comment]
I'm taking a stab at Python 3 support now

**Comment by amstocker** [comment]
Thanks moreati!

**Comment by BrendanBenshoof** [comment]
Superseded by #26
